# .streamlit/secrets.toml

[secrets]
api_key = "6TsBFihrXk+m4J5TsK353UL11KJTneUlu9Pn28By1JVl3fz9AN0F7OtPLAq+2zhX"


[connections.gsheets]
worksheet = "WeeklyPicksStorage" # The title of your entire sheet file
credentials = """

{
  "type": "service_account",
  "project_id": "collegefootball-469817",
  "private_key_id": "9f4fa95ee7baa515c7f86e2f41dc83904ba7c86a",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDJ71yhdObeddXw\nIuF2qqAJK/NakG30gGzEwC4yhshDrg41s7UThMCJ9KfX9LAPVFGJSaQR7VWs8yL9\nphxqyMFsqa88SVL2ZeLmOcPnL++cMLIidvkRIKZloVpW1ihp1/QrmR5gar2uruFu\nJe5MlZ05gmFb9G7+e6eHKT9P8nG7VT00wfyF3qlDSX+vP6A5rBaEuueTx0DTpfhA\nJxCg1HjEMm2/3vGMxfIFJMt5y6KCxHKMeuns2Y8G0uWacUNM/qbxxbnbozYeg66Q\npCjx5kHV/XJO5Bw3QrHOtNYKFi3Jw8VjPaK2G+S4qEBLx0x2LA32aHwFo0ViUrUU\n420d6GPhAgMBAAECggEAIRzNcTJEq0TiTGrD0tweuvJIiNi3Fwk6DLdAvAtK6oIv\nlVG/BxDVK6oBHdHjTtgyOJNpQoFK8724xqQG8+Gwift3Hykc4AeMAdmGDLJZFaEM\njMc6hzr13iNrt2KNpPGC+eU1THUkXnERySiSH1/HNMdy5Iu76aHoMisq1Ra53JBO\nlIucnv+D9a9KLkaVhMvt4nCsudnaBERZDr3RTHyyhtIHe5buHVcZz/U10d3h/z4B\nqSu+Vz3t6TQrZFXOPoeI+zCxTIUvUubSLBsZ4jhiunxZyX2F518Io3cazsMsyzIE\nlEPh/D9o29P1G/y8UFg4sWJXJrG3m0l9c4lzoApaywKBgQDjeS0aQEyKcceQmmFL\nclGZhwG5bs4Ynp5sP6lp5GMu1cPpBshKxIZFxiVcBPTuOHCVzYu9Tgr7YzdQGG26\nFuSKKmmHzi8JYZqJvnFOiW8caS/ADavGtaRvAFwGcfQZG4F29yyQUmjodhV5crII\nAxfeZ3vTSJU6ty+R73KzfZRADwKBgQDjQkz5XUIasUVVrhhmx2Pz+9DzStL5WNY0\nUvDUDLW6bdElH6epSfoDt88eS0PVsoMB/KKA/DqwGlVOxOmRhGKpQwzbifhjks1p\n4ciPmampThhuMCHrmPcIRrA65v7Mq7buToRKnhOmvxHqKjxErIYo6+NL3mV+9D5o\nT9txR6otDwKBgQDaNLyKSRHjYH/ye9VHPXN/Vd3Wlq9HOKl555vJA5gNLmwPFj1+\nU4UGW6ws2GhoOGXvncwlnT61pZhC0hw3/Yvf6g1vg97lHebTqYchsn6Of2yZy8Nz\nC32gKXUdjaR9jUAk8bii/Rq7m8K/zMFxJB56b0R+Ckt0lpMgZ9Tcz2MuCwKBgQDa\nYNuWxAbBn5cAvkq0eOWTjmc7YqtY8ATmQs0o9w2qF9zhz4lNI8kbyYU9lxWYQ/Gf\n9yQwzi+XCbbv+kh3jL9B5yxzyiDljivVkyEm3IIsLt9LAvWVb2fyi/rMnyw5gMhI\nNyroiP5ZPUH5wpwnYaGJsSK5xPvDAvD1S8eTE0p0AQKBgQCFhB4o8Vyf0za4fUp8\nSWMZfDEJx497spYvLl4SwaNYPHHpleN1PGh8vU+T575djbCdgnLy+rdf6UuBQwoh\nkOXN2DuKmLi0Gapnp/OCLHx6UwU74U2FqicLrySby12jVW4O8xtP1gSY3bSfpTzj\nATHH+tcnNl/NZCkd8ZwUVNfFyw==\n-----END PRIVATE KEY-----\n",
  "client_email": "wkoehn@collegefootball-469817.iam.gserviceaccount.com",
  "client_id": "109593282621195842965",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/wkoehn%40collegefootball-469817.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

